name: Deploy Preview

on: [pull_request]

jobs:
  create_neon_branch:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      db_url: ${{ steps.create_branch.outputs.db_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{github.event.after}}

      - name: Get Commit Message
        id: get_pr_commit_message
        run: |
          echo commit_message=$(git log --format=%B -n 1 ${{github.event.after}}) >> $GITHUB_OUTPUT

      - name: Get PR SHA
        id: get_pr_commit_sha
        run: echo "short_sha=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_OUTPUT

      - name: Create Branch
        uses: neondatabase/create-branch-action@v2
        id: create_branch
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch_name: ${{ steps.get_pr_commit_sha.short_sha}} ${{steps.get_pr_commit_message.outputs.commit_message}}
          api_key: ${{ secrets.NEON_API_KEY }}
          username: ${{ secrets.PG_USERNAME }}
          password: ${{ secrets.PG_PASSWORD }}

      - name: Run Prisma Migrate
        env:
          DATABASE_URL: ${{ steps.create_branch.outputs.db_url}}/neondb
          DIRECT_DATABASE_URL: ${{ steps.create_branch.outputs.db_url}}/neondb
        run: |
          touch .env
          echo DIRECT_DATABASE_URL=${DIRECT_DATABASE_URL} >> .env
          echo DATABASE_URL=${DATABASE_URL} >> .env
          npx prisma generate
          npx prisma migrate deploy

  # If migration fails, exit workflow?

  Deploy-Preview:
    needs: create_neon_branch
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=preview --token=${VERCEL_TOKEN}
          vercel build --token=${VERCEL_TOKEN}
          preview_url=$(vercel deploy --prebuilt --token=${VERCEL_TOKEN})
          echo "preview_url=${preview_url}" >> $GITHUB_OUTPUT
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy.outputs.preview_url }}
